# Generated by Django 3.1.5 on 2021-01-16 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('writer', models.CharField(max_length=45)),
                ('date', models.DateTimeField(auto_now=True)),
                ('views', models.IntegerField(default=0)),
                ('content', models.TextField()),
            ],
        ),
    ]
