# Generated by Django 3.1.5 on 2021-01-16 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
