# Generated by Django 3.1.5 on 2021-01-16 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0002_auto_20210116_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
