# Generated by Django 3.1.5 on 2021-01-16 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0004_auto_20210116_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
