# Generated by Django 3.1.5 on 2021-01-16 14:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0005_auto_20210116_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
    ]
