# Generated by Django 3.1.5 on 2021-01-16 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0006_auto_20210116_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='date',
            field=models.DateField(blank=True, default='2021.01.16'),
        ),
    ]
