# Generated by Django 3.1.5 on 2021-02-18 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0008_auto_20210116_1429'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faq',
            name='views',
        ),
    ]
