# Generated by Django 3.1.3 on 2021-01-19 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0009_auto_20210116_1302'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purpose',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('use_purpose', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_start', models.DateTimeField()),
                ('reservation_end', models.DateTimeField()),
                ('headcount', models.IntegerField()),
                ('required_equipment', models.TextField(null=True)),
                ('group_name', models.CharField(max_length=80, null=True)),
                ('username', models.CharField(max_length=90)),
                ('phone_number', models.CharField(max_length=12)),
                ('user_type', models.IntegerField()),
                ('purpose', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rsv.purpose')),
                ('room_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.room')),
            ],
        ),
    ]
