# Generated by Django 3.1.5 on 2021-01-28 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsv', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='required_equipment',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='reservation_end',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='reservation_start',
        ),
        migrations.AddField(
            model_name='reservation',
            name='admit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reservation',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='reservation',
            name='user_number',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
