# Generated by Django 3.1.3 on 2021-02-01 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsv', '0003_auto_20210128_0748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='end_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='start_time',
            field=models.DateTimeField(),
        ),
    ]
