# Generated by Django 3.1.6 on 2021-02-24 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsv', '0004_auto_20210201_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='admit',
            field=models.IntegerField(default=0),
        ),
    ]
