# Generated by Django 3.1.6 on 2021-02-27 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsv', '0007_auto_20210227_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='rsv_date',
            field=models.DateTimeField(),
        ),
    ]
