# Generated by Django 3.1.5 on 2021-03-10 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsv', '0009_auto_20210227_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='authentic_code',
            field=models.IntegerField(default=100000),
        ),
    ]
