# Generated by Django 3.1.5 on 2021-01-10 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210110_1405'),
    ]

    operations = [
        migrations.CreateModel(
            name='SourceImg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(null=True, upload_to='source/')),
            ],
        ),
    ]
