# Generated by Django 3.1.5 on 2021-01-11 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_sourceimg'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='subname',
            field=models.CharField(default='', max_length=45),
        ),
    ]
