# Generated by Django 3.1.5 on 2021-01-12 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_room_subname'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='photo',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
