# Generated by Django 3.1.5 on 2021-01-12 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20210112_1536'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SourceImg',
        ),
    ]
