# Generated by Django 3.1.5 on 2021-01-16 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_delete_sourceimg'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='code',
            field=models.CharField(default='', max_length=45),
        ),
        migrations.AddField(
            model_name='building',
            name='english_name',
            field=models.CharField(default='', max_length=45),
        ),
    ]
