# Generated by Django 3.1.5 on 2021-03-10 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Authentication',
        ),
    ]
