# Generated by Django 3.1.6 on 2021-02-08 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('director', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
